name       : orc
version    : 0.4.26
release    : 5
source     :
    - https://gstreamer.freedesktop.org/src/orc/orc-0.4.26.tar.xz : 7d52fa80ef84988359c3434e1eea302d077a08987abdde6905678ebcad4fa649
homepage   : http://code.entropywave.com/orc/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
summary    : The Oil Runtime Compiler
component  : programming.library
emul32     : yes
optimize   : speed
description: |
    Orc is a just-in-time compiler implemented as a library and set of associated tools for compiling and executing simple programs that operate on arrays of data.  Orc is unlike other general-purpose JIT engines: the Orc bytecode and language is designed so that it can be readily converted into SIMD instructions.  This translates to interesting language features and limitations: Orc has built-in capability for SIMD-friendly operations such as shuffling, saturated addition and subtraction, but only works on arrays of data.  This makes Orc good for applications such as image processing, audio processing, array math, and signal analysis.
patterns   :
    - devel :
        - /usr/bin
        - /usr/share/aclocal
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
