name        : orc
version     : 0.4.24
release     : 3
source      :
    - http://gstreamer.freedesktop.org/src/orc/orc-0.4.24.tar.xz : 338cd493b5247300149821c6312bdf7422a3593ae98691fc75d7e4fe727bd39b
homepage    : http://code.entropywave.com/orc/
license     :
    - BSD-2-Clause
    - BSD-3-Clause
summary     : The Oil Runtime Compiler
description : |
    Orc is a just-in-time compiler implemented as a library and set of associated tools for compiling and executing simple programs that operate on arrays of data.  Orc is unlike other general-purpose JIT engines: the Orc bytecode and language is designed so that it can be readily converted into SIMD instructions.  This translates to interesting language features and limitations: Orc has built-in capability for SIMD-friendly operations such as shuffling, saturated addition and subtraction, but only works on arrays of data.  This makes Orc good for applications such as image processing, audio processing, array math, and signal analysis.
patterns    :
    - devel:
        - /usr/bin
        - /usr/share/aclocal
setup       : |
    %configure --disable-static
build       : |
    %make
install     : |
    %make_install
